version: '3.7'
services:
  router:
    image: roki/igmng-web-router:1.0.0
    container_name: roki-igmng-router
    tty: true
    volumes:
      - "../igrouter:/home/igmng/bin"
    ports:
      - "3000:3000"
    expose:
      - "3000"
    working_dir: /home/igmng/bin
    build:
      context: ../
      dockerfile: ./containers/igrouter_webserver/Dockerfile
    command: /bin/bash -c 'make run'
    networks:
      - igmng-net
  db:
    image: mysql:8.0
    tty: true
    container_name: roki-igmng-mysql
    ports:
      - "127.0.0.1:3306:3306"
    expose:
      - "3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
      - ./db/conf:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    networks:
      - igmng-net
    cap_add:
      - SYS_NICE
  cron:
    image: roki/igmng-cron:1.0.0
    container_name: roki-igmng-cron
    tty: true
    depends_on:
      - router
      - db
    volumes:
      - ./igmng_cron/crontab:/var/spool/cron/crontabs/root
    build:
      context: ../
      dockerfile: ./containers/igmng_cron/Dockerfile
    command: /bin/bash -c 'busybox crond -l 8 -L /dev/stderr -f'
    networks:
      - igmng-net
  grafana:
    image: grafana/grafana
    container_name: roki-igmng-grafana
    volumes:
      - ./grafana_data:/var/lib/grafana
    environment:
      GF_SERVER_HTTP_PORT: 3001
    ports:
      - 3001:3001
    networks:
      - igmng-net
    user: "104"
    depends_on:
      - db

networks:
  igmng-net:
    driver: bridge
