name: CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1.3
        with:
          ghc-version: '8.6.5'
          enable-stack: latest
      - name: Cache
        uses: actions/cache@v2
        id: stack-cache
        with:
          path: ~/.stack
          key: stack-v2-${{ runner.os }}-${{ hashFiles('stack.yaml') }}
      - name: Setup Stack
        if: steps.stack-cache.outputs.cache-hit != 'true'
        run: |
          stack config set system-ghc --global true
          stack config set install-ghc --global false
      - name: Build
        run: |
          stack --local-bin-path . install
          ./igmng --help
